DROP TABLE IF EXISTS PRODUCT;
create table PRODUCT (
	id INT,
	name VARCHAR(150),
	description VARCHAR(150),
	price DECIMAL(4,2),
	PRIMARY KEY(id)
);
insert into PRODUCT (id, name, description, price) values (1, 'Table Cloth 90x90 Colour', 'MetLife, Inc.', 48.94);
insert into PRODUCT (id, name, description, price) values (2, 'Squeeze Bottle', 'Wright Medical Group N.V.', 25.26);
insert into PRODUCT (id, name, description, price) values (3, 'Juice - Ocean Spray Cranberry', 'Capital Bank Financial Corp.', 17.69);
insert into PRODUCT (id, name, description, price) values (4, 'Cheese - Ricotta', 'Sophiris Bio, Inc.', 18.26);
insert into PRODUCT (id, name, description, price) values (5, 'Butcher Twine 4r', 'Azure Power Global Limited', 26.29);
insert into PRODUCT (id, name, description, price) values (6, 'Island Oasis - Wildberry', 'KalVista Pharmaceuticals, Inc.', 11.24);
insert into PRODUCT (id, name, description, price) values (7, 'Salt - Rock, Course', 'Navigator Holdings Ltd.', 45.53);
insert into PRODUCT (id, name, description, price) values (8, 'Salmon Atl.whole 8 - 10 Lb', 'Abeona Therapeutics Inc.', 48.98);
insert into PRODUCT (id, name, description, price) values (9, 'Oven Mitt - 13 Inch', 'Pattern Energy Group Inc.', 44.53);
insert into PRODUCT (id, name, description, price) values (10, 'Soup V8 Roasted Red Pepper', 'Dermira, Inc.', 48.46);
insert into PRODUCT (id, name, description, price) values (11, 'Capers - Ox Eye Daisy', 'National Oilwell Varco, Inc.', 23.04);
insert into PRODUCT (id, name, description, price) values (12, 'Pork Salted Bellies', 'Western Union Company (The)', 23.4);
insert into PRODUCT (id, name, description, price) values (13, 'Radish', 'Advance Auto Parts Inc', 20.75);
insert into PRODUCT (id, name, description, price) values (14, 'Flour - Chickpea', 'FairPoint Communications, Inc.', 39.26);
insert into PRODUCT (id, name, description, price) values (15, 'Wine - Toasted Head', 'John Hancock Tax-Advantaged Global Shareholder Yield Fund', 36.59);
insert into PRODUCT (id, name, description, price) values (16, 'Wheat - Soft Kernal Of Wheat', 'Double Eagle Acquisition Corp.', 40.47);
insert into PRODUCT (id, name, description, price) values (17, 'Mangostein', 'Drive Shack Inc.', 25.25);
insert into PRODUCT (id, name, description, price) values (18, 'Tomatoes - Hot House', 'The Rubicon Project, Inc.', 32.82);
insert into PRODUCT (id, name, description, price) values (19, 'Cod - Fillets', 'Deutsche Bank AG', 6.4);
insert into PRODUCT (id, name, description, price) values (20, 'Table Cloth 54x72 White', 'SMART Global Holdings, Inc.', 25.2);
insert into PRODUCT (id, name, description, price) values (21, 'Crush - Orange, 355ml', 'Axcelis Technologies, Inc.', 18.53);
insert into PRODUCT (id, name, description, price) values (22, 'Urban Zen Drinks', 'United Technologies Corporation', 8.44);
insert into PRODUCT (id, name, description, price) values (23, 'Rabbit - Whole', 'W.P. Carey Inc.', 40.57);
insert into PRODUCT (id, name, description, price) values (24, 'Cheese - St. Paulin', 'The Meet Group, Inc.', 36.52);
insert into PRODUCT (id, name, description, price) values (25, 'Cheese - Grana Padano', 'Huaneng Power International, Inc.', 25.92);
insert into PRODUCT (id, name, description, price) values (26, 'Pork Casing', 'Ashford Hospitality Trust Inc', 33.94);
insert into PRODUCT (id, name, description, price) values (27, 'Cookie Dough - Double', 'Golar LNG Limited', 47.33);
insert into PRODUCT (id, name, description, price) values (28, 'Asparagus - Mexican', 'Atlantic American Corporation', 22.48);
insert into PRODUCT (id, name, description, price) values (29, 'Chicken - Tenderloin', 'Wells Fargo & Company', 34.11);
insert into PRODUCT (id, name, description, price) values (30, 'Mushroom - White Button', 'Blackrock Core Bond Trust', 11.58);
insert into PRODUCT (id, name, description, price) values (31, 'Goat - Whole Cut', 'Southwest Bancorp, Inc.', 36.57);
insert into PRODUCT (id, name, description, price) values (32, 'Chicken Thigh - Bone Out', 'WisdomTree Barclays Negative Duration U.S. Aggregate Bond Fund', 14.1);
insert into PRODUCT (id, name, description, price) values (33, 'Orange - Canned, Mandarin', 'AmTrust Financial Services, Inc.', 47.76);
insert into PRODUCT (id, name, description, price) values (34, 'Devonshire Cream', 'Blackrock Municipal 2020 Term Trust', 24.12);
insert into PRODUCT (id, name, description, price) values (35, 'Macaroons - Two Bite Choc', 'Lazard World Dividend & Income Fund, Inc.', 5.73);
insert into PRODUCT (id, name, description, price) values (36, 'Pop Shoppe Cream Soda', 'Origo Acquisition Corporation', 16.54);
insert into PRODUCT (id, name, description, price) values (37, 'Mace Ground', 'Blackrock MuniYield New Jersey Fund, Inc.', 45.35);
insert into PRODUCT (id, name, description, price) values (38, 'Tuna - Yellowfin', 'Nordstrom, Inc.', 46.16);
insert into PRODUCT (id, name, description, price) values (39, 'Chicken - Whole', 'Five Point Holdings, LLC', 34.41);
insert into PRODUCT (id, name, description, price) values (40, 'Steel Wool', 'CombiMatrix Corporation', 39.06);
insert into PRODUCT (id, name, description, price) values (41, 'Beef - Rib Eye Aaa', 'Aceto Corporation', 13.59);
insert into PRODUCT (id, name, description, price) values (42, 'Radish - Pickled', 'Patriot National, Inc.', 39.07);
insert into PRODUCT (id, name, description, price) values (43, 'Rice Paper', 'AmTrust Financial Services, Inc.', 24.69);
insert into PRODUCT (id, name, description, price) values (44, 'Potatoes - Fingerling 4 Oz', 'VanEck Vectors Biotech ETF', 29.7);
insert into PRODUCT (id, name, description, price) values (45, 'Vaccum Bag 10x13', 'AutoNation, Inc.', 17.01);
insert into PRODUCT (id, name, description, price) values (46, 'Chocolate - Chips Compound', 'Double Eagle Acquisition Corp.', 40.7);
insert into PRODUCT (id, name, description, price) values (47, 'Potato - Sweet', 'Atwood Oceanics, Inc.', 20.1);
insert into PRODUCT (id, name, description, price) values (48, 'Cheese - Brie Roitelet', 'FlexShares US Quality Large Cap Index Fund', 10.04);
insert into PRODUCT (id, name, description, price) values (49, 'Scallops 60/80 Iqf', 'Williams Partners LP', 33.76);
insert into PRODUCT (id, name, description, price) values (50, 'Container - Clear 32 Oz', 'Global X Longevity Thematic ETF', 49.51);
insert into PRODUCT (id, name, description, price) values (51, 'Beef - Top Butt', 'Kennametal Inc.', 42.48);
insert into PRODUCT (id, name, description, price) values (52, 'Ice Cream - Life Savers', 'Intermolecular, Inc.', 34.77);
insert into PRODUCT (id, name, description, price) values (53, 'Ice Cream - Chocolate', 'ServiceNow, Inc.', 30.22);
insert into PRODUCT (id, name, description, price) values (54, 'Flour - Whole Wheat', 'CardConnect Corp.', 12.53);
insert into PRODUCT (id, name, description, price) values (55, 'Table Cloth 72x144 White', 'BLDRS Asia 50 ADR Index Fund', 8.27);
insert into PRODUCT (id, name, description, price) values (56, 'Wine - Two Oceans Sauvignon', 'Builders FirstSource, Inc.', 6.52);
insert into PRODUCT (id, name, description, price) values (57, 'Doilies - 7, Paper', 'Platform Specialty Products Corporation', 22.16);
insert into PRODUCT (id, name, description, price) values (58, 'Rabbit - Saddles', 'Ternium S.A.', 46.66);
insert into PRODUCT (id, name, description, price) values (59, 'Cookies Cereal Nut', 'Arc Logistic Partners LP', 5.88);
insert into PRODUCT (id, name, description, price) values (60, 'Shrimp - Baby, Cold Water', 'First Internet Bancorp', 39.77);
insert into PRODUCT (id, name, description, price) values (61, 'Chickensplit Half', 'Southern California Edison Company', 21.33);
insert into PRODUCT (id, name, description, price) values (62, 'Coffee Guatemala Dark', 'Associated Banc-Corp', 43.24);
insert into PRODUCT (id, name, description, price) values (63, 'Flour - Pastry', 'Deutsch Bk Contingent Cap Tr V', 31.54);
insert into PRODUCT (id, name, description, price) values (64, 'Lettuce - Boston Bib - Organic', 'Videocon d2h Limited', 49.8);
insert into PRODUCT (id, name, description, price) values (65, 'Split Peas - Green, Dry', 'Paycom Software, Inc.', 35.3);
insert into PRODUCT (id, name, description, price) values (66, 'Chips - Assorted', 'Westamerica Bancorporation', 30.85);
insert into PRODUCT (id, name, description, price) values (67, 'Pasta - Fettuccine, Egg, Fresh', 'Calgon Carbon Corporation', 48.98);
insert into PRODUCT (id, name, description, price) values (68, 'Bread - Pita, Mini', 'China TechFaith Wireless Communication Technology Limited', 36.84);
insert into PRODUCT (id, name, description, price) values (69, 'Ham - Cooked Italian', 'Kingsway Financial Services, Inc.', 46.48);
insert into PRODUCT (id, name, description, price) values (70, 'Cheese - Mix', 'Alimera Sciences, Inc.', 49.12);
insert into PRODUCT (id, name, description, price) values (71, 'Beer - Molson Excel', 'Protagonist Therapeutics, Inc.', 38.21);
insert into PRODUCT (id, name, description, price) values (72, 'Buffalo - Striploin', 'Stratasys, Ltd.', 28.16);
insert into PRODUCT (id, name, description, price) values (73, 'Venison - Liver', 'Bryn Mawr Bank Corporation', 30.67);
insert into PRODUCT (id, name, description, price) values (74, 'Beef - Tenderloin Tails', 'MFC Bancorp Ltd.', 18.99);
insert into PRODUCT (id, name, description, price) values (75, 'Olives - Nicoise', 'Yintech Investment Holdings Limited', 32.87);
insert into PRODUCT (id, name, description, price) values (76, 'Pastry - Cherry Danish - Mini', 'Erie Indemnity Company', 32.98);
insert into PRODUCT (id, name, description, price) values (77, 'Chocolate - Mi - Amere Semi', 'Neonode Inc.', 38.6);
insert into PRODUCT (id, name, description, price) values (78, 'Wine - Red, Lurton Merlot De', 'Umpqua Holdings Corporation', 42.51);
insert into PRODUCT (id, name, description, price) values (79, 'Langers - Cranberry Cocktail', 'Digi International Inc.', 32.71);
insert into PRODUCT (id, name, description, price) values (80, 'Chicken - Whole Roasting', 'Tile Shop Hldgs, Inc.', 45.94);
insert into PRODUCT (id, name, description, price) values (81, 'Raspberries - Frozen', 'Juniper Networks, Inc.', 13.66);
insert into PRODUCT (id, name, description, price) values (82, 'Soup - Knorr, Chicken Gumbo', 'BlackRock Income Investment Quality Trust', 27.29);
insert into PRODUCT (id, name, description, price) values (83, 'Doilies - 12, Paper', 'OFG Bancorp', 29.57);
insert into PRODUCT (id, name, description, price) values (84, 'Juice - Orange', 'Evertec, Inc.', 18.07);
insert into PRODUCT (id, name, description, price) values (85, 'Bread Crumbs - Panko', 'Gabelli Multi-Media Trust Inc. (The)', 13.19);
insert into PRODUCT (id, name, description, price) values (86, 'Pork - Back, Long Cut, Boneless', 'Qwest Corporation', 10.61);
insert into PRODUCT (id, name, description, price) values (87, 'Pastry - Raisin Muffin - Mini', 'Hunter Maritime Acquisition Corp.', 40.29);
insert into PRODUCT (id, name, description, price) values (88, 'Fennel - Seeds', 'CubeSmart', 40.07);
insert into PRODUCT (id, name, description, price) values (89, 'Wine - Tio Pepe Sherry Fino', 'MGM Growth Properties LLC', 26.67);
insert into PRODUCT (id, name, description, price) values (90, 'Yeast Dry - Fleischman', 'Pioneer Municipal High Income Advantage Trust', 12.98);
insert into PRODUCT (id, name, description, price) values (91, 'Kellogs All Bran Bars', 'Guggenheim Strategic Opportunities Fund', 10.62);
insert into PRODUCT (id, name, description, price) values (92, 'Pate - Liver', 'Ruby Tuesday, Inc.', 30.06);
insert into PRODUCT (id, name, description, price) values (93, 'Cheese - Blue', 'Baltimore Gas & Electric Company', 16.1);
insert into PRODUCT (id, name, description, price) values (94, 'Extract - Raspberry', 'Pimco High Income Fund', 19.55);
insert into PRODUCT (id, name, description, price) values (95, 'Cheese - Cheddar, Old White', 'Myriad Genetics, Inc.', 7.77);
insert into PRODUCT (id, name, description, price) values (96, 'Towel Multifold', 'Aratana Therapeutics, Inc.', 30.61);
insert into PRODUCT (id, name, description, price) values (97, 'Grand Marnier', 'Adams Diversified Equity Fund, Inc.', 41.5);
insert into PRODUCT (id, name, description, price) values (98, 'Cheese - Roquefort Pappillon', 'Pacific Ethanol, Inc.', 28.31);
insert into PRODUCT (id, name, description, price) values (99, 'Glass - Juice Clear 5oz 55005', 'PNC Financial Services Group, Inc. (The)', 47.79);
insert into PRODUCT (id, name, description, price) values (100, 'Cornish Hen', 'Fifth Street Asset Management Inc.', 32.66);
